### ISSUE TITLE
pluggy._manager.PluginValidationError: unknown hook 'pytest_warning_captured' in plugin 'pytest_buildkite'

### ISSUE THREAD

**Issue by 8enmann** [pytest-buildkite/pytest-buildkite#30]
**Describe the bug**
I'm getting the following error when running with pytest-buildkite

```
============================= test session starts ==============================
platform linux -- Python 3.9.12, pytest-7.1.1, pluggy-1.0.0 -- /usr/local/bin/python
cachedir: .pytest_cache
rootdir: /var/lib/buildkite-agent/builds/<REDACTED>, configfile: setup.cfg
plugins: buildkite-0.3.0, anyio-3.5.0, trio-0.7.0, typeguard-2.12.1
collected 4 items                                                              
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/_pytest/main.py", line 268, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/_pytest/main.py", line 321, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/_pytest/main.py", line 332, in pytest_collection
INTERNALERROR>     session.perform_collect()
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/_pytest/main.py", line 659, in perform_collect
INTERNALERROR>     self.config.pluginmanager.check_pending()
INTERNALERROR>   File "/usr/local/lib/python3.9/site-packages/pluggy/_manager.py", line 262, in check_pending
INTERNALERROR>     raise PluginValidationError(
INTERNALERROR> pluggy._manager.PluginValidationError: unknown hook 'pytest_warning_captured' in plugin <module 'pytest_buildkite' from '/usr/local/lib/python3.9/site-packages/pytest_buildkite/__init__.py'>
```

**To Reproduce**
Not sure how to reproduce.... 

**Expected behavior**
No error

**Additional context**
I only just started seeing this. Maybe a dependency of pytest-buildkite is not pinned properly?

**Comment by 8enmann** [comment]
Ah! It's because there's a breaking change in pytest 7.1.0
https://docs.pytest.org/en/stable/changelog.html#breaking-changes
